import { useEffect } from "react";
import Head from "next/head";
import userStore from "@/stores/userStore";
import { Box } from "@chakra-ui/react";
import theme from "@/styles/theme";
import { useRouter } from "next/router";
import toast from "react-hot-toast";
import MyCredentialsPage from "./mycredentials";
import LoginPage from "./login";

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Bit Benders - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        minHeight="100vh"
        bg={theme.colors.background}
        color="white"
        fontFamily="Montserrat"
      >
        <LoginPage />
      </Box>
    </Box>
  );
}
